// data.js - Contains the game data (categories, items, sizes)

const gameData = {
  categories: [
    {
      name: "Data Size",
      unit: "Bytes",
      items: [
        { name: "Single Bit", value: 0.125, unit: "bit" },
        { name: "Single Character (ASCII)", value: 1, unit: "Byte" },
        { name: "Short Text Message (SMS)", value: 160, unit: "Bytes" },
        {
          name: "Empty Document (txt)",
          value: 1024,
          unit: "Bytes",
          display_unit: "KB",
        },
        { name: "Tweet (text only)", value: 280, unit: "Bytes" },
        {
          name: "Simple Email (text only)",
          value: 5120,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "Contact Information (vCard)",
          value: 10240,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "Small Icon (e.g., favicon)",
          value: 20480,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "Simple Webpage (HTML, no images)",
          value: 51200,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "Short Email with Images",
          value: 204800,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "Standard QR Code",
          value: 71680,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "Low-Res Photo (Smartphone)",
          value: 512000,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "Single Page Document (DOC, PDF) Text",
          value: 512000,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "Simple Presentation (PPT) Mostly text",
          value: 1024000,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "E-book (Simple Text)",
          value: 1024000,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "MP3 Audio File (1 minute)",
          value: 2097152,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "High-Res Photo (Smartphone)",
          value: 8388608,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Single Page Document (DOC, PDF) With images",
          value: 5242880,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Full Page Scan",
          value: 10485760,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Typical Website Homepage",
          value: 10485760,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Short Video Clip (Social Media)",
          value: 20971520,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Standard Presentation (PPT) With images and media",
          value: 20971520,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Mobile Game (Simple)",
          value: 52428800,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Web Based Game",
          value: 52428800,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Standard Quality Song (MP3)",
          value: 10485760,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Average Podcast Episode",
          value: 62914560,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "PC Game (Early 2000s)",
          value: 524288000,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Average Android/iOS App",
          value: 209715200,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Full E-book (with images)",
          value: 52428800,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "CD Quality Audio Track",
          value: 62914560,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "High-Quality Photo (DSLR)",
          value: 52428800,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "HD Movie Trailer",
          value: 209715200,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Mobile Game (Complex)",
          value: 524288000,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Webpage with many Images",
          value: 209715200,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Netflix Episode (Low Quality)",
          value: 524288000,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "3D Model (Simple)",
          value: 104857600,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "PC Game (Mid 2000s)",
          value: 2147483648,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Full Length Movie (Low Quality)",
          value: 1048576000,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Netflix Episode (Standard Quality)",
          value: 1048576000,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Uncompressed RAW Photo File (DSLR)",
          value: 78643200,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Large PDF File (graphics-intensive)",
          value: 524288000,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Virtual Machine (VM) Image",
          value: 10737418240,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Operating System ISO (small distro)",
          value: 1572864000,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "High-Quality Movie (720p)",
          value: 4294967296,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Modern PC Game",
          value: 107374182400,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Database Backup (small)",
          value: 5368709120,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "BluRay Quality Movie",
          value: 53687091200,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "AAA PC Game Install",
          value: 214748364800,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Operating System ISO (Windows/macOS)",
          value: 10737418240,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "4K Movie",
          value: 107374182400,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Uncompressed HD Video (1 hour)",
          value: 214748364800,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Database Backup (Medium)",
          value: 107374182400,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Large CAD File",
          value: 536870912000,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Small SSD Drive",
          value: 274877906944,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Database Backup (Large)",
          value: 1073741824000,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Video Game Installation (AAA Title)",
          value: 214748364800,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Medium Hard Drive",
          value: 2147483648000,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Genome Sequencing Data (Human)",
          value: 1073741824000,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Digital Archive Collection",
          value: 1099511627776,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Large Hard Drive",
          value: 2199023255552,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Full Backup of a Small Business",
          value: 54975581388800,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Raw Video Footage (feature film)",
          value: 109951162777600,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Data Warehouse (Small)",
          value: 109951162777600,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Scientific Research Data (Large)",
          value: 1099511627776000,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Large Data Warehouse",
          value: 1099511627776000,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Full Backup of a Medium Business",
          value: 549755813888000,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Social Media Data for a Large Event",
          value: 1099511627776000,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Petabyte-Scale Data",
          value: 1099511627776000,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Data Center Storage (Small)",
          value: 1125899906842624,
          unit: "Bytes",
          display_unit: "PB",
        },
        {
          name: "Large Social Media Platform Data",
          value: 112589990684262400,
          unit: "Bytes",
          display_unit: "PB",
        },
        {
          name: "Astronomy Data (Telescope Survey)",
          value: 11258999068426240,
          unit: "Bytes",
          display_unit: "PB",
        },
        {
          name: "Data Center Storage (Large)",
          value: 112589990684262400,
          unit: "Bytes",
          display_unit: "PB",
        },
        {
          name: "Genome Sequencing Data (Population)",
          value: 112589990684262400,
          unit: "Bytes",
          display_unit: "PB",
        },
        {
          name: "Exabyte-Scale Data",
          value: 1152921504606846976,
          unit: "Bytes",
          display_unit: "EB",
        },
        {
          name: "Internet Archive Data",
          value: 115292150460684697600,
          unit: "Bytes",
          display_unit: "EB",
        },
        {
          name: "Scientific Simulation Data (Climate)",
          value: 11529215046068469760,
          unit: "Bytes",
          display_unit: "EB",
        },
        {
          name: "Global Internet Traffic (Daily)",
          value: 1152921504606846976000,
          unit: "Bytes",
          display_unit: "ZB",
        },
      ],
    },
    {
      name: "Luminous Flux",
      unit: "Lumens",
      items: [
        { name: "Candle", value: 13, unit: "lm" },
        { name: "Moonlight (Full Moon)", value: 0.05, unit: "lm" },
        { name: "Firefly", value: 0.001, unit: "lm" },
        { name: "LED Indicator Light", value: 0.1, unit: "lm" },
        { name: "Christmas Light (single bulb)", value: 5, unit: "lm" },
        { name: "Night Light", value: 15, unit: "lm" },
        { name: "Mobile Phone Flashlight (low)", value: 30, unit: "lm" },
        { name: "Small Penlight", value: 50, unit: "lm" },
        { name: "40W Incandescent Bulb", value: 450, unit: "lm" },
        { name: "Standard Flashlight", value: 100, unit: "lm" },
        { name: "60W Incandescent Bulb", value: 800, unit: "lm" },
        { name: "Desk Lamp", value: 400, unit: "lm" },
        { name: "Mobile Phone Flashlight (High)", value: 500, unit: "lm" },
        { name: "LED Bulb (5W)", value: 400, unit: "lm" },
        { name: "75W Incandescent Bulb", value: 1100, unit: "lm" },
        { name: "100W Incandescent Bulb", value: 1600, unit: "lm" },
        { name: "LED Bulb (10W)", value: 800, unit: "lm" },
        { name: "Car Headlight (Low Beam)", value: 700, unit: "lm" },
        { name: "Car Headlight (High Beam)", value: 1200, unit: "lm" },
        { name: "LED Bulb (15W)", value: 1200, unit: "lm" },
        { name: "Halogen Bulb (50W)", value: 900, unit: "lm" },
        { name: "Streetlight (Residential)", value: 5000, unit: "lm" },
        { name: "LED Flood Light (Small)", value: 3000, unit: "lm" },
        { name: "Bright Room Light", value: 4000, unit: "lm" },
        { name: "Stage Light (Spotlight)", value: 10000, unit: "lm" },
        { name: "LED Flood Light (Large)", value: 20000, unit: "lm" },
        { name: "Streetlight (Highway)", value: 15000, unit: "lm" },
        { name: "Lightning Bolt (peak)", value: 1000000000000, unit: "lm" },
        { name: "Sun (per square meter)", value: 130000, unit: "lm" },
      ],
    },
    {
      name: "Spiciness",
      unit: "Scoville Heat Units",
      items: [
        { name: "Bell Pepper", value: 0, unit: "SHU" },
        { name: "Banana Pepper", value: 0, unit: "SHU" },
        { name: "Pimiento Pepper", value: 0, unit: "SHU" },
        { name: "Pepperoncini", value: 100, unit: "SHU" },
        { name: "Anaheim Pepper", value: 500, unit: "SHU" },
        { name: "Poblano Pepper", value: 1250, unit: "SHU" },
        { name: "Ancho Pepper", value: 1500, unit: "SHU" },
        { name: "Hungarian Wax Pepper", value: 5000, unit: "SHU" },
        { name: "Espelette Pepper", value: 4000, unit: "SHU" },
        { name: "Pasilla Pepper", value: 2000, unit: "SHU" },
        { name: "Jalapeno Pepper", value: 5000, unit: "SHU" },
        { name: "Serrano Pepper", value: 15000, unit: "SHU" },
        { name: "Cayenne Pepper", value: 50000, unit: "SHU" },
        { name: "Tabasco Pepper", value: 50000, unit: "SHU" },
        { name: "Bird's Eye Chili", value: 100000, unit: "SHU" },
        { name: "Scotch Bonnet Pepper", value: 200000, unit: "SHU" },
        { name: "Habanero Pepper", value: 250000, unit: "SHU" },
        { name: "Datil Pepper", value: 300000, unit: "SHU" },
        { name: "Rocotillo Pepper", value: 1500, unit: "SHU" },
        { name: "Aji Amarillo", value: 50000, unit: "SHU" },
        { name: "Manzano Pepper", value: 30000, unit: "SHU" },
        { name: "Pequin Pepper", value: 60000, unit: "SHU" },
        { name: "Chiltepin Pepper", value: 70000, unit: "SHU" },
        { name: "Madame Jeanette", value: 250000, unit: "SHU" },
        { name: "Devil's Tongue Pepper", value: 325000, unit: "SHU" },
        { name: "Red Savina Habanero", value: 577000, unit: "SHU" },
        { name: "Ghost Pepper (Bhut Jolokia)", value: 1000000, unit: "SHU" },
        { name: "Naga Viper Pepper", value: 1382118, unit: "SHU" },
        { name: "7 Pot Douglah Pepper", value: 1853936, unit: "SHU" },
        { name: "Trinidad Moruga Scorpion", value: 2000000, unit: "SHU" },
        { name: "Carolina Reaper", value: 2200000, unit: "SHU" },
        { name: "Pepper X", value: 3180000, unit: "SHU" },
        { name: "Wasabi (freshly grated)", value: 100, unit: "SHU" },
        { name: "Horseradish (freshly grated)", value: 50, unit: "SHU" },
        { name: "Ginger (fresh)", value: 15, unit: "SHU" },
        { name: "Spicy Mustard", value: 1000, unit: "SHU" },
        { name: "Sriracha", value: 2200, unit: "SHU" },
        { name: "Gochujang", value: 400, unit: "SHU" },
        { name: "Hot Sauce (Mild)", value: 500, unit: "SHU" },
        { name: "Hot Sauce (Medium)", value: 5000, unit: "SHU" },
        { name: "Hot Sauce (Hot)", value: 50000, unit: "SHU" },
        { name: "Crushed Red Pepper Flakes", value: 30000, unit: "SHU" },
        { name: "Fresh Chili Oil", value: 10000, unit: "SHU" },
        { name: "Chipotle Pepper", value: 2500, unit: "SHU" },
        { name: "Arbol Pepper", value: 30000, unit: "SHU" },
        { name: "Guajillo Pepper", value: 5000, unit: "SHU" },
        { name: "Pasilla Oaxaca Pepper", value: 4000, unit: "SHU" },
        { name: "Cascabel Pepper", value: 2500, unit: "SHU" },
        { name: "Aji Charapita", value: 50000, unit: "SHU" },
        { name: "Fatalii Pepper", value: 125000, unit: "SHU" },
      ],
    },
    {
      name: "Sound Level",
      unit: "Decibels",
      items: [
        { name: "Breathing", value: 10, unit: "dB" },
        { name: "Rustling Leaves", value: 20, unit: "dB" },
        { name: "Whisper", value: 30, unit: "dB" },
        { name: "Quiet Library", value: 40, unit: "dB" },
        { name: "Residential Area at Night", value: 40, unit: "dB" },
        { name: "Soft Music", value: 40, unit: "dB" },
        { name: "Refrigerator Humming", value: 45, unit: "dB" },
        { name: "Normal Conversation", value: 60, unit: "dB" },
        { name: "Office Environment", value: 60, unit: "dB" },
        { name: "Vacuum Cleaner", value: 70, unit: "dB" },
        { name: "Busy Street", value: 70, unit: "dB" },
        { name: "Washing Machine", value: 70, unit: "dB" },
        { name: "Hair Dryer", value: 80, unit: "dB" },
        { name: "Alarm Clock", value: 80, unit: "dB" },
        { name: "Food Blender", value: 85, unit: "dB" },
        { name: "Heavy Traffic", value: 85, unit: "dB" },
        { name: "Motorcycle", value: 90, unit: "dB" },
        { name: "Lawnmower", value: 90, unit: "dB" },
        { name: "Subway Train", value: 95, unit: "dB" },
        { name: "Power Drill", value: 95, unit: "dB" },
        { name: "Garbage Truck", value: 100, unit: "dB" },
        { name: "Chainsaw", value: 100, unit: "dB" },
        { name: "Snowmobile", value: 100, unit: "dB" },
        { name: "Concert Speakers", value: 110, unit: "dB" },
        { name: "Car Horn", value: 110, unit: "dB" },
        { name: "Rock Concert", value: 115, unit: "dB" },
        { name: "Ambulance Siren", value: 120, unit: "dB" },
        { name: "Thunderclap", value: 120, unit: "dB" },
        { name: "Jet Engine (100ft away)", value: 130, unit: "dB" },
        { name: "Jackhammer", value: 130, unit: "dB" },
        { name: "Gunshot", value: 140, unit: "dB" },
        { name: "Fireworks", value: 150, unit: "dB" },
        { name: "Air horn", value: 120, unit: "dB" },
        { name: "Tire Blowout", value: 150, unit: "dB" },
        { name: "Quiet rural area", value: 35, unit: "dB" },
        { name: "Rain", value: 50, unit: "dB" },
        { name: "Dishwasher", value: 60, unit: "dB" },
        { name: "City traffic", value: 80, unit: "dB" },
        { name: "Construction site", value: 100, unit: "dB" },
        { name: "Inside a moving car", value: 70, unit: "dB" },
        { name: "Factory", value: 85, unit: "dB" },
        { name: "Movie Theater", value: 75, unit: "dB" },
        { name: "Nightclub", value: 105, unit: "dB" },
        { name: "Passing train", value: 90, unit: "dB" },
        { name: "Children playing", value: 80, unit: "dB" },
        { name: "Birdsong", value: 50, unit: "dB" },
        { name: "Running water", value: 65, unit: "dB" },
        { name: "Police siren", value: 120, unit: "dB" },
        { name: "Baby crying", value: 110, unit: "dB" },
      ],
    },
    {
      name: "Length",
      unit: "Meters",
      items: [
        {
          name: "Planck Length (theoretical limit)",
          value: 1.6e-35,
          unit: "m",
        },
        {
          name: "Diameter of a Quark (theoretical upper limit)",
          value: 1e-18,
          unit: "m",
        },
        { name: "Hydrogen Atom Diameter", value: 1e-10, unit: "m" },
        { name: "Small Molecule (e.g., Water)", value: 3e-10, unit: "m" },
        { name: "Diameter of a DNA double helix", value: 2e-9, unit: "m" },
        { name: "Thickness of a Cell Membrane", value: 7.5e-9, unit: "m" },
        { name: "Diameter of a Ribosome", value: 2.5e-8, unit: "m" },
        { name: "Diameter of a Virus (small)", value: 2e-8, unit: "m" },
        { name: "Diameter of a Virus (large)", value: 3e-7, unit: "m" },
        { name: "Wavelength of Violet Light", value: 4e-7, unit: "m" },
        { name: "Diameter of a Eukaryotic Nucleus", value: 5e-6, unit: "m" },
        { name: "Wavelength of Red Light", value: 7e-7, unit: "m" },
        { name: "Diameter of a Bacterium (small)", value: 1e-6, unit: "m" },
        { name: "Diameter of a Bacterium (large)", value: 1e-5, unit: "m" },
        { name: "Width of Human Hair", value: 8e-5, unit: "m" },
        { name: "Length of an Ant", value: 5e-3, unit: "m" },
        { name: "Length of a Grain of Rice", value: 7.5e-3, unit: "m" },
        { name: "Length of a US Quarter", value: 2.4e-2, unit: "m" },
        { name: "Height of a Chicken Egg", value: 5.5e-2, unit: "m" },
        { name: "Length of a Foot", value: 3.0e-1, unit: "m" },
        { name: "Height of a Basketball Hoop", value: 3.05, unit: "m" },
        { name: "Average Human Height", value: 1.75, unit: "m" },
        { name: "Length of a Car", value: 4.5, unit: "m" },
        { name: "Height of a Giraffe", value: 5.0, unit: "m" },
        { name: "Length of a Blue Whale", value: 3.0e1, unit: "m" },
        { name: "Wingspan of a Boeing 747", value: 6.8e1, unit: "m" },
        { name: "Height of the Statue of Liberty", value: 9.3e1, unit: "m" },
        { name: "Length of a Football Field", value: 1.1e2, unit: "m" },
        {
          name: "Height of the Great Pyramid of Giza",
          value: 1.47e2,
          unit: "m",
        },
        { name: "Height of the Eiffel Tower", value: 3.3e2, unit: "m" },
        { name: "Depth of the Mariana Trench", value: 1.1e4, unit: "m" },
        { name: "Height of Mount Everest", value: 8.8e3, unit: "m" },
        { name: "Length of Manhattan Island", value: 2.1e4, unit: "m" },
        { name: "Diameter of the Grand Canyon", value: 2.9e4, unit: "m" },
        { name: "Diameter of the Moon", value: 3.5e6, unit: "m" },
        { name: "Circumference of the Earth", value: 4.0e7, unit: "m" },
        { name: "Diameter of the Earth", value: 1.3e7, unit: "m" },
        { name: "Distance from Earth to Moon", value: 3.8e8, unit: "m" },
        { name: "Diameter of the Sun", value: 1.4e9, unit: "m" },
        { name: "Distance from Earth to Sun (1 AU)", value: 1.5e11, unit: "m" },
        {
          name: "Diameter of Solar System (to Kuiper Belt)",
          value: 9.0e12,
          unit: "m",
        },
        { name: "Distance to Proxima Centauri", value: 4.0e16, unit: "m" },
        { name: "Diameter of the Oort Cloud", value: 3.0e16, unit: "m" },
        { name: "1 Light Year", value: 9.5e15, unit: "m" },
        { name: "Diameter of the Milky Way Galaxy", value: 1.0e21, unit: "m" },
        { name: "Distance to the Andromeda Galaxy", value: 2.5e22, unit: "m" },
        { name: "Diameter of the Local Group", value: 1.0e23, unit: "m" },
        { name: "Size of the Observable Universe", value: 9.3e26, unit: "m" },
        {
          name: "Great Wall of Hercules-Corona Borealis",
          value: 3.0e25,
          unit: "m",
        },
        { name: "Virgo Supercluster diameter", value: 1.1e24, unit: "m" },
      ],
    },
  ],
};

export { gameData };
