// data.js - Contains the game data (categories, items, sizes)

const gameData = {
  categories: [
    {
      name: "Data Size",
      unit: "Bytes",
      items: [
        { name: "Single Bit", value: 0.125, unit: "bit" },
        { name: "Single Character (ASCII)", value: 1, unit: "Byte" },
        { name: "Short Text Message (SMS)", value: 160, unit: "Bytes" },
        {
          name: "Empty Document (txt)",
          value: 1024,
          unit: "Bytes",
          display_unit: "KB",
        },
        { name: "Tweet (text only)", value: 280, unit: "Bytes" },
        {
          name: "Simple Email (text only)",
          value: 5120,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "Contact Information (vCard)",
          value: 10240,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "Small Icon (e.g., favicon)",
          value: 20480,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "Simple Webpage (HTML, no images)",
          value: 51200,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "Short Email with Images",
          value: 204800,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "Standard QR Code",
          value: 71680,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "Low-Res Photo (Smartphone)",
          value: 512000,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "Single Page Document (DOC, PDF) Text",
          value: 512000,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "Simple Presentation (PPT) Mostly text",
          value: 1024000,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "E-book (Simple Text)",
          value: 1024000,
          unit: "Bytes",
          display_unit: "KB",
        },
        {
          name: "MP3 Audio File (1 minute)",
          value: 2097152,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "High-Res Photo (Smartphone)",
          value: 8388608,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Single Page Document (DOC, PDF) With images",
          value: 5242880,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Full Page Scan",
          value: 10485760,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Typical Website Homepage",
          value: 10485760,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Short Video Clip (Social Media)",
          value: 20971520,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Standard Presentation (PPT) With images and media",
          value: 20971520,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Mobile Game (Simple)",
          value: 52428800,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Web Based Game",
          value: 52428800,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Standard Quality Song (MP3)",
          value: 10485760,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Average Podcast Episode",
          value: 62914560,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "PC Game (Early 2000s)",
          value: 524288000,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Average Android/iOS App",
          value: 209715200,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Full E-book (with images)",
          value: 52428800,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "CD Quality Audio Track",
          value: 62914560,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "High-Quality Photo (DSLR)",
          value: 52428800,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "HD Movie Trailer",
          value: 209715200,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Mobile Game (Complex)",
          value: 524288000,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Webpage with many Images",
          value: 209715200,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Netflix Episode (Low Quality)",
          value: 524288000,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "3D Model (Simple)",
          value: 104857600,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "PC Game (Mid 2000s)",
          value: 2147483648,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Full Length Movie (Low Quality)",
          value: 1048576000,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Netflix Episode (Standard Quality)",
          value: 1048576000,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Uncompressed RAW Photo File (DSLR)",
          value: 78643200,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Large PDF File (graphics-intensive)",
          value: 524288000,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "Virtual Machine (VM) Image",
          value: 10737418240,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Operating System ISO (small distro)",
          value: 1572864000,
          unit: "Bytes",
          display_unit: "MB",
        },
        {
          name: "High-Quality Movie (720p)",
          value: 4294967296,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Modern PC Game",
          value: 107374182400,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Database Backup (small)",
          value: 5368709120,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "BluRay Quality Movie",
          value: 53687091200,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "AAA PC Game Install",
          value: 214748364800,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Operating System ISO (Windows/macOS)",
          value: 10737418240,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "4K Movie",
          value: 107374182400,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Uncompressed HD Video (1 hour)",
          value: 214748364800,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Database Backup (Medium)",
          value: 107374182400,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Large CAD File",
          value: 536870912000,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Small SSD Drive",
          value: 274877906944,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Database Backup (Large)",
          value: 1073741824000,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Video Game Installation (AAA Title)",
          value: 214748364800,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Medium Hard Drive",
          value: 2147483648000,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Genome Sequencing Data (Human)",
          value: 1073741824000,
          unit: "Bytes",
          display_unit: "GB",
        },
        {
          name: "Digital Archive Collection",
          value: 1099511627776,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Large Hard Drive",
          value: 2199023255552,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Full Backup of a Small Business",
          value: 54975581388800,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Raw Video Footage (feature film)",
          value: 109951162777600,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Data Warehouse (Small)",
          value: 109951162777600,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Scientific Research Data (Large)",
          value: 1099511627776000,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Large Data Warehouse",
          value: 1099511627776000,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Full Backup of a Medium Business",
          value: 549755813888000,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Social Media Data for a Large Event",
          value: 1099511627776000,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Petabyte-Scale Data",
          value: 1099511627776000,
          unit: "Bytes",
          display_unit: "TB",
        },
        {
          name: "Data Center Storage (Small)",
          value: 1125899906842624,
          unit: "Bytes",
          display_unit: "PB",
        },
        {
          name: "Large Social Media Platform Data",
          value: 112589990684262400,
          unit: "Bytes",
          display_unit: "PB",
        },
        {
          name: "Astronomy Data (Telescope Survey)",
          value: 11258999068426240,
          unit: "Bytes",
          display_unit: "PB",
        },
        {
          name: "Data Center Storage (Large)",
          value: 112589990684262400,
          unit: "Bytes",
          display_unit: "PB",
        },
        {
          name: "Genome Sequencing Data (Population)",
          value: 112589990684262400,
          unit: "Bytes",
          display_unit: "PB",
        },
        {
          name: "Exabyte-Scale Data",
          value: 1152921504606846976,
          unit: "Bytes",
          display_unit: "EB",
        },
        {
          name: "Internet Archive Data",
          value: 115292150460684697600,
          unit: "Bytes",
          display_unit: "EB",
        },
        {
          name: "Scientific Simulation Data (Climate)",
          value: 11529215046068469760,
          unit: "Bytes",
          display_unit: "EB",
        },
        {
          name: "Global Internet Traffic (Daily)",
          value: 1152921504606846976000,
          unit: "Bytes",
          display_unit: "ZB",
        },
      ],
    },
    {
      name: "Luminous Flux",
      unit: "Lumens",
      items: [
        { name: "Candle", value: 13, unit: "lm" },
        { name: "Moonlight (Full Moon)", value: 0.05, unit: "lm" },
        { name: "Firefly", value: 0.001, unit: "lm" },
        { name: "LED Indicator Light", value: 0.1, unit: "lm" },
        { name: "Christmas Light (single bulb)", value: 5, unit: "lm" },
        { name: "Night Light", value: 15, unit: "lm" },
        { name: "Mobile Phone Flashlight (low)", value: 30, unit: "lm" },
        { name: "Small Penlight", value: 50, unit: "lm" },
        { name: "40W Incandescent Bulb", value: 450, unit: "lm" },
        { name: "Standard Flashlight", value: 100, unit: "lm" },
        { name: "60W Incandescent Bulb", value: 800, unit: "lm" },
        { name: "Desk Lamp", value: 400, unit: "lm" },
        { name: "Mobile Phone Flashlight (High)", value: 500, unit: "lm" },
        { name: "LED Bulb (5W)", value: 400, unit: "lm" },
        { name: "75W Incandescent Bulb", value: 1100, unit: "lm" },
        { name: "100W Incandescent Bulb", value: 1600, unit: "lm" },
        { name: "LED Bulb (10W)", value: 800, unit: "lm" },
        { name: "Car Headlight (Low Beam)", value: 700, unit: "lm" },
        { name: "Car Headlight (High Beam)", value: 1200, unit: "lm" },
        { name: "LED Bulb (15W)", value: 1200, unit: "lm" },
        { name: "Halogen Bulb (50W)", value: 900, unit: "lm" },
        { name: "Streetlight (Residential)", value: 5000, unit: "lm" },
        { name: "LED Flood Light (Small)", value: 3000, unit: "lm" },
        { name: "Bright Room Light", value: 4000, unit: "lm" },
        { name: "Stage Light (Spotlight)", value: 10000, unit: "lm" },
        { name: "LED Flood Light (Large)", value: 20000, unit: "lm" },
        { name: "Streetlight (Highway)", value: 15000, unit: "lm" },
        { name: "Lightning Bolt (peak)", value: 1000000000000, unit: "lm" },
        { name: "Sun (per square meter)", value: 130000, unit: "lm" },
      ],
    },
  ],
};

export { gameData };
